spring.application.name=ai-campus-complaint-system


# ==============================
# DATABASE
# ==============================

spring.datasource.url=jdbc:mysql://localhost:3306/complaint_management_system?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC

spring.datasource.username=root

spring.datasource.password=Adarsh@7978

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ==============================
# JPA / HIBERNATE
# ==============================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.use_sql_comments=true


# ==============================
# SERVER
# ==============================

server.port=8080